# Use the README file as a reference to customize settings.

Ad:
  fields:
    default: page, company, created_at, updated_at
    list: company, page, created_at, updated_at
    form: page_id, company_id
  relationships: company, issue, page
  application: Application
  filters: company, issue
  #search: company, page


