Page:
  fields:
    default: title, url, companies, page_nr, comment, issue
    form: title, image, companies, page_nr, comment, issue
    list: image_preview, companies, title, page_nr, issue, created_at, updated_at
    options:
      templates:
        image: carrierwave
        companies: company_select
  relationships: issue
  application: Application
  filters: issue, page_nr
  search: title, page_nr, comment