Page:
  fields:
    default: title, company, image, page_nr, comment, issue_id
    form: title, company, image, page_nr, comment, issue_id
    list: image_preview, company, title, page_nr, issue_id, created_at, updated_at
    options:
      templates:
        image: carrierwave
  relationships: issue
  application: Application
  filters: issue, page_nr
  search: title, company, page_nr, comment