development:
  adapter: sqlite3
  encoding: utf8
  database: nguoidep_development
  pool: 5
  username: nguoidep
  password: nguoidep

test:
  adapter: sqlite3
  encoding: utf8
  database: nguoidep_test
  pool: 5
  username: nguoidep
  password: nguoidep

production:
  adapter: sqlite3
  encoding: utf8
  database: nguoidep_production
  pool: 5
  username: nguoidep
  password: nguoidep
