development:
  adapter: sqlite3
  encoding: utf8
  database: nguoidep_development
  pool: 5
  username: nguoidep
  password: nguoidep

test:
  adapter: sqlite3
  encoding: utf8
  database: nguoidep_test
  pool: 5
  username: nguoidep
  password: nguoidep

production:
  adapter: sqlite3
  encoding: utf8
  database: nguoidep_production
  pool: 5
  username: nguoidep
  password: nguoidep

proxied-appfog:
  adapter: mysql2
  database: d8e11af817d0d41dbbee94b16d93259e5
  username: u6robzx6voe48
  password: pRO4p1qkifW5c
  port: 10000
  host: 127.0.0.1

upload:
  adapter: mysql2
  encoding: utf8
  database: nguoidep_development
  pool: 5
  username: nguoidep
  password: nguoidep