development:
  adapter: mysql2
  encoding: utf8
  database: nguoidep_development
  pool: 5
  username: nguoidep
  password: nguoidep

test:
  adapter: mysql2
  encoding: utf8
  database: nguoidep_test
  pool: 5
  username: nguoidep
  password: nguoidep

production:
  adapter: myssql2
  encoding: utf8
  database: nguoidep_production
  pool: 5
  username: nguoidep
  password: nguoidep
